// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksAPI.Data;

#nullable disable

namespace NZWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241212094915_Seeding Data for diff and reg")]
    partial class SeedingDatafordiffandreg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9563ff0-d73d-4470-a25a-a5c1f0d4a2cd"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("d84b719a-e6e3-4eec-8003-50a954c86188"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("2a821b42-497c-4375-b368-aadc825141e7"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fedf87f-41c3-4646-8a91-b5200a8a33e4"),
                            Code = "ACK",
                            Name = "Auckland",
                            RegionImageUrl = "https://imgix.theurbanlist.com/content/article/Rangitoto-Todd-Eyre.-ATEED_RMH_005-(1).jpg"
                        },
                        new
                        {
                            Id = new Guid("6c861a39-f5ee-43e1-a105-c290aae8361c"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://www.newzealand.com/assets/Tourism-NZ/Northland-Bay-of-Islands/1000011333__aWxvdmVrZWxseQo_FocalPointCropWzM1MiwxMDI0LDMyLDYzLDc1LCJqcGciLDY1LDIuNV0.jpg"
                        },
                        new
                        {
                            Id = new Guid("8e9c527f-2f2e-4c77-bdea-76dcd2dd95ca"),
                            Code = "BOP",
                            Name = "Bay of Plenty"
                        },
                        new
                        {
                            Id = new Guid("b950f1f4-db81-4824-bc58-94b8139b7795"),
                            Code = "WGL",
                            Name = "Wellington",
                            RegionImageUrl = "https://www.neverendingvoyage.com/wp-content/uploads/2022/11/main-wellington-walks-skyline.jpg"
                        },
                        new
                        {
                            Id = new Guid("67dfa371-fe56-4eea-bb4d-308bfb8b7803"),
                            Code = "NSN",
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = new Guid("235b54a5-d6e8-4693-ab4b-f178995b0016"),
                            Code = "STL",
                            Name = "SouthLand",
                            RegionImageUrl = "https://www.newzealand.com/assets/Tourism-NZ/Southland/img-1536309346-4874-7451-B315794E-ED00-E5F3-899FFD38B13A4799__aWxvdmVrZWxseQo_FocalPointCropWzM1MiwxMDI0LDQ5LDYyLDc1LCJqcGciLDY1LDIuNV0.jpg"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalksAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
